### ISSUE TITLE
Ability to control logging level

### ISSUE THREAD

**Issue by nikkonrom** [AdminAnticaptcha/anticaptcha-npm#1]
While solving captcha, checks for done task writes to console every 2 seconds, and if solving captcha takes a long time, application logs becomes unreadable. It's ok for development purposes, but in production environment would be nice to suppress this messages by setting a log level variable (env or module config)

**Comment by EstebanDworak** [comment]
Totally agree is super annoying to have logs happening every 2 seconds especially when you are solving a bunch of captchas.

**Comment by EstebanDworak** [comment]
I can add a "debug mode" variable to enable or dissable console logging. This is super annoying.

**Comment by AdminAnticaptcha** [comment]
Hi, added shutUp() function for this.

**Comment by EstebanDworak** [comment]
Thanks a lot!
