### ISSUE TITLE
Report incorrect image captcha must be empty or need to send captcha id?

### ISSUE THREAD

**Issue by d2m22** [AdminAnticaptcha/anticaptcha-npm#11]
Report incorrect image captcha must be empty or need to send captcha id?
`ac.reportIncorrectImageCaptcha();`

**Comment by AdminAnticaptcha** [comment]
Index page says:

Report last solved image captcha as incorrect (must read [this](https://anti-captcha.com/apidoc/methods/reportIncorrectImageCaptcha) before using):

ac.reportIncorrectImageCaptcha();
