### ISSUE TITLE
hCaptcha NodeJS Fails for Runescape.com

### ISSUE THREAD

**Issue by Tjonna** [AdminAnticaptcha/anticaptcha-npm#14]
https://anti-captcha.com/apidoc/task-types/HCaptchaTaskProxyless

Following these instructions and these settings:
const websiteUrl = "https://secure.runescape.com/m=account-creation/g=oldscape/create_account";
const websiteKey = "33f96e6a-38cd-421b-bb68-7806e1764460";

A lot of the g_response are wrong, this is not the case for Python, here I never get incorrect tokens.
Could you check for me?

Correct Token example:
`
W0_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5IjoiOTBkTU1YMnJVcWlZM3JFanArY25NcjNWY0FLbXRkQXVrQTBHOFZUTkxwSDNGOFY3NC91blZ0YTBHT1RCTUg1aFUxQTREZlVjMVBTTHhPSHlHTmRKYU5RVGtvblFQVWFtbXV0UVJhS0RYcXgxYmxpRVo2WklGQVNkUXNaNGFtdGVQT0VaYTZ5TkNiL256NmkydHR2Z2dReGd3VzdCYkk4c0JEM0FqTDZ2NWZmUFlzeExCR0FUak9nQWovMkxaTEwyRXBoK0RNY29qZmtVQjBQVXN0QWRRUWE2V0hKNnFuNnFFaS9XQVRGWXlidXR5LzFHQ0FnMjJKTGlYMUtTcXp6dW5oUmlnRE1TMTlqTlNSS2c2a2NkQUtVMTBkbFY1SDdUdkx6em9PVzdxTVNLbE5JNEtxK29vc0p1MlhPSTBNeDY1YllJOXpKQ3BDUlBEdjlGTzdNUlRWV01PN1FwejM3KzlCaDBZSGVZZXUxUWE2blpQM3ZyQnRKSXlvWk4xcDBWSkxpV3ViajBZdkVDRytEbGJiT0g2ZFdPVW9GTm53Q2FLRlRiTzVUczBRT0hOWkpDK1JEcVVvaHFZUlh3ZXh0amZGUUpHdG1kcXRQU1pqR08yT0tXZlIxZEVucG15Z0dMcWpTS2UyZkFGVmZSUjJPV0svb3I4U3dMdGFnVThBdlZBNE1xdGVESkJJbE81OVZ2L1lKai96NHVGZWJmQTZxcWZ1ZFVKTjk3ajhhbUptVnNyRk1oSXdHN25SRVc5eURaWkxQMkFMMmVwOW1jbGw3SzkrMGIvY2gwUjkrV1FCN1lmWEhSZUpHUkJ2dG83MElaNlB3WUdrczFsVTI4L09CditQeGdIcnN6eWMwcVN1ZHJ6QVM4MGZvaDJDMlQrS3JFQlRZL3d6TjlJOVp2blhyYjc1dnlYSkw2U1Nuc3hJbnVmWndwQVNPZFZENDVFZTdXWng1Y2ZFelBsK0pUcUNHTzZ1TlpYckFUU1h5TmdlM1l3MFV2RVNTQ1dsUG9tUHF2VjJKaUh3V0VCYVRwU0p1WVBZZW9jR0Erc3ZlRjhNK0pTNVZvdHhSL1JOOHVPRnl0YVNocEowbXgyYmdsbGJOc0RUYkpFYkdBZjYvLzlSZm04cEh5a1cwNi9WUU0zZEwvY3AxYUVvQlpubnJTS0lNRlV3Qi9hUU1lMUJ2eGRvMEE1YUszclFGVU9CbkhvQzdHS3NRK3pybmF6dUxsL25IRUN0MmFjN2d6LzVwUnJsMHZXTjNqbitKQTJaTHRHZDlJMlpIQXcyNmlpWmEwbWpEY3BzdXExcE1rNnpaVHgzZjV1NWRjMXJmSTVGSE5VU1NDSkpQU05RRnhUUlMxM01mL2NUdzlkUjZWbGlIZVNDYVByeXBBU3JvcCtjdTRPZHhEM0xCTG1zRTEzbGFHejhVdXpNcGlSOHRBWWErcXFCY0psWFdCK2p0Y2VVNVF5ZWN2aWNvRGd0M1hmZWJlTDlMc1FUL3lvWTNackgwM1VoSEx4WWJ4R1JWYnQ5VXNNWmp0aUhaRVMwSnM3YzVWc1FnbUladkg4aTY1TkkwTnU4SnljNVN0Uk5sREdiLzJhRXl3U0N0bWl6bUdTWGZKUVorNWRQNHlWdz09Uk1mT01xR0xEYm5NUTNURSIsInNpdGVrZXkiOiIzM2Y5NmU2YS0zOGNkLTQyMWItYmI2OC03ODA2ZTE3NjQ0NjAiLCJleHAiOjE2NjQ4MjU0MTEsInBkIjowfQ.GZ3OCzjabe2pmB1LlHA9IK3NuZ4LMRDH2SXZX7Ujpx4
`

Incorrect Tokens:
`W0_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5IjoibktnUTJzZHV2MXVDNXpVWWdpaHRiajBtT2Zaa2pQU25XaVBuTm5wS3BwUGl0cHFRTlA4Sm5vSEk5aGxBZDMwRkl3K0lKYkJLTnJZdHRPa29RUWdRL3BqcG1Vby9WdmFOWVNkd2NSaW9TQ3pFZm0xSVV3amtkK0hQODB0RWd6MTRHSDRBMXhUT1MyMnBNQkVKUklRZDluaGNITFR0d3NrZ0h0eEpRVk1zNEZoUnhDMGVwRU9lUGY0MXo5TUhQUUpEUTRpNlZuMWgyQzh1WGVQbEQzZGV6dy9Eb1NabTBYYktwT05NOU5pdGJFY3pRMytqUGhoNHpIblVOTGRhWkhYUVVZSDhQd0w2RTR4eTNkZ1VRaWc4aDg2aStrclpCTlFKYkdEMTI5TDNJeDJoYlBwc011NUp4WTJoVGVPRUR2Y241anR6cDB5NXZKSlV5dklsR1h3MTZ3VkluUng2UDFyZjRqdnUwck5mRVc4Zk9pNFFDQmlKRHpiMjdSUU9VK0t2QWdPR242dFFOcG1ra1laclhZRkIvVmcxaDdSM1JFVmFsNjBHL3NTUThqZUllRlJrbUxZNFBwRnhWSTBiYkk5eTBveXpiMjcrdXJjZEdBbTI1UHZLTXkwUWgrRVoveHB3bHZVa0FuNURFek9xS1lmRUdwM3AzZDJub3U3a084TDY5L3dlZ2tWOVkvNWQ4TkNDb3lXaHZoRUd1S3hkV3pNQkFoZHREMEYwZSsxQVBXWkZaM3laTTJhVWNuQjYvQ3k2MEhXZmNUYXduZGVFZ3hicVlwRDJPdGJNYndoNXNhQnFxamdzUUN1RWFyMjlsYk10bTNSQlBNVC8va3gxT2JISmdFUEkrUDZUUlZ6d1F1R1laamZVYnFjV1hCWVVkNlEzVEpMOVRHQzJ5dGl6bTNvTDJ1Tno3WEtXeGRwQktJcWNxV0xyUDQ5TzBIdnhqTzh4Wnk3UWpDdVZsTzNZTHhsUWRhVVh3YmhnRnVlNCttNCttTjh3QnA3NGprSTZhK21NODBzNnl3VTZwYVlNNTFadEJEZUdRUDg2cHU0YmJKVXNxWDVDdVVSMGgvdGgvSEI2bDJjSk1tQktZL1ZGSDFJMVhVL0R5Szg2eCtpcmoremNRcHJBdi9teFdhcFBubjhjNFVUYW1kTGxFTlZIenk2TndIbWdRa3pRaEN1aENsYkhLZkdva0d4R25uKzFRZEJBMGNYdmYxMDlnWkdrMit6aG1mTFhFRjVTZm03Wnk2dFRUSEJGYVpFd0NoVmpUOHFvS0ZrendYRE5pZ1krWmp1aUJJeXpPenYvK2dHemdnSG5mbzh5UDVUVk1ZYWNZZThJZXF4cGdiOWJDQzNxb2ZUQTdocnd3VTcrTFNTT1NPOS9ZMVdyaUd1ZlN6V2FPOXlCbUtxcXdwVEl4L2w4TWJPM3FiaFlQd1J5bDFZTnlVN0pCOXhXVGIzZEwyUjBzSGwrYmd0UHU0MWtDN2k3cFI5WS9kVzVUQ0lhdUpSVVZzRGlqa2pwWUpYVGlKWGIzMjA0NWpTNjFlc3YxRGRaa0VwUVcrRzlvelNjWk0vWTBhcjB5eUhyeWd5M3g2VWF2WW9HZ0s0Y1pFclBjbGdReTF5VWE2blh0MW5DdGZEZkt4a09CU2hYUXNCMnkwa3VFUW9TZE1mUWg1WVFKUE1neDRScXNBYlFDV2JJNXdMNGI3TzZiYytBRGd0UTF3bTY3amxsaEgzZWJ3Mjcxd3NsZStoc3YzcHA0NjVJaGhjdjVVdkxteFFVU1ZLc1V2OElnR2pJdVArTGxFREN5dGlnTWtlM1RYVWNLNkV1VlpVPWR5MmZQNUxaU3NiN2xyaTUiLCJzaXRla2V5IjoiMzNmOTZlNmEtMzhjZC00MjFiLWJiNjgtNzgwNmUxNzY0NDYwIiwiZXhwIjoxNjY0ODI1MDgyLCJwZCI6MH0.cBgR7SKH6YZyAdRU2mhdb-DZtObJUZ0tj-Ro3ArXPF0

W0_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5IjoiWXpEWFNDUlBJTFRWeWNVcDZrWTNqWGtlREZqV3Q3ZHNuSzZid1JzT3NnOHRFb1g1K2xsRGR0OTk5T09laUtFcXJNOEF6QnRnaHhKVmxQQWVYZzZyOUo0ditUc2pQZWo1TVk5VnFBbnM5ekh6c01TTzZWM0VzaElwVnQ1WEVGSHNtYjJaZ1Y2R2sybkhGU0lsQW1mN0JhUStpMFNkT2VUWkdLQ2RVUkl0ZUQvbE96a0ZkYW1wa2tsWFR5NjJHY0hpWVZIL0p0Rnk2WUhmZUxUMCttb1Ywb3RhYW8xeGY5U1h5RjhEQ2dNTm5nbEVvWFdsN1B4SGhsRk5uU3B3WWRxOTJxenpkZ0M3eGl0Q0V6R3ZlZ2RPS3dGNWZTM1AwaU1Wczd3d25CRHA1cldMV1plQml4VjFBSjdtNmV5Q1BMY3IzazhoN21lRFhyOUpSakErbDVZSEYwN3I5ajRLY2xvYmVCeTI5ZXgvb2J4di9oWXoySXlNdmYxQmtvTEZUSmJZa0JYT2ZaWUI3V2lkSXR1WUZOVVJ1OFNobzRjS2wyMlNmSlp5TWdzN3BZYy9uUjIrUFVQc24zeUhJaUZsaTBNZXlIenpYNnBrd3dlbUhXNWVFQjlXNm1mazhxYmcxUnM1dlhoNHpxczNiVUJPU2JUNjVzZVJyNEFSbUNXbnlubHZSbys0MHg2Zm5GRXppVUJ6UlROandyS0E4eVVuS1NxZEVUbU5BRWdscWFjdDFLMTNrcjIwOWpCRUJ6REErRFY1b3lZdDVVb1RrblZoVDNwdnFrZVVXamVhYm1Nd1lkSGlSMzRGRXRta2hmWjd3cWd0Q0JvcTN4cTNNb0ZWVjdacHE0WTVML1hldVBWUG54Tkc0dzdyRk5adzZzQ2c4eTdYOG9ZbzVOQzR0L2R6UEVPa1RFV0U2M2cxajQwbUNpOVh6YkhGMkpvc0FFa2xwanpLUVNXTzBTdCsxZ0JqMDY2cFhGclQrcGRsamVNSXdsdlZMOHQ5bXRLR1d5T2VTb0NnWDExMHdVSzZSRnYxZWpZN015a2lYdmUrZkxCMzZYbU13VmhsSWcvL21TUVlleWxNcXVqQlI0emd1RFg2aDB3VlJrTS9PWEY1bld5WlJNa1JZYWJXV2VpQTBvS0xrVXkxZ2VhY2E5SW44eHErVFh3bTNOK1hrRWFkMi82dkVPZXJlNXE1bHIxMjFFQ1NxVlhqR2NHNVhzakF5S0ppa1VaZ3RoZDJnSy9LOS9iaHdIWXZoZHBJdWUvQVQ0NGw0dExWeldGNUFrL2pvNFFBY3VlRHc3aE5WR2xPVmJTbXpob0pjZHU4cERtbE9XS2R2aFZFZVRRTVhLTXR4bEVZRm1LcGJDU3ptaERRMzdjWGFCYldlZlZWVDFHbUNHS2lRK0p6TlptZEh5SU9rbmNycWI1YTRLeDIrc2QreENab1BtTWRTdmU2QmgzRXgvSFNLNzlzcWhjb2FYaE01ZG9uSXlwWGdCL0czWTVqYnpWQnZvd1ZqSktSanJ6SnluOUxkSmFoVXYyVjQ3T3lyOWlXbHMyN29lR1VGWmhobkkzSGN4MEk1TDFKRkMzYUJMQWFyZ2JLSDhYYnRuaWsvWG1aVmY0RS9xSXJnQ05SVHQvWkVZT0oiLCJzaXRla2V5IjoiMzNmOTZlNmEtMzhjZC00MjFiLWJiNjgtNzgwNmUxNzY0NDYwIiwiZXhwIjoxNjY0ODI1MTgzLCJwZCI6MH0.g6jGPsqmKfR4gvFUZcMWaLO2AcawcW1d9l5ryS0luiA

W0_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5IjoiVW1UbGNXcmV2N2F0eStJazlKRG9OazA2OU1GZUh3S2tubU0weEkxcWZXbzhKZnlsOVJVK3Z2c2V4NlJRb2JLQUNLcC9PZGMvRkFxU0hqWWNBKzE1L3FPbzFQaXpjQUtyZXlqL2VKa3Rpa2FJYVgwOFB6S3Z6ejZOcmZzUE5rczZ2VnJTVmR0RGc5M1c1eHRWalNoTzg2aHcycDdscEw5bTVYQmZrYVRBbmFkYzdORlovVE1oN1F1ZGxSaktsZGgzcDFVbm1vbHhxTWFsVmdpekVNV0dWREFyWUpkSWtBUHZ0cHFHN2xYdnJ2UHNuTDlHY0JvYWw0MFJ2WVQ2cmJCWTRlc2ltaExGWmxoL05vMFJ2cjNkZHNKdEc5Q0QyaFdDR2hNOUJkeUVkWm90eXpYMXBWdFA4M2VOejB3dlE3UTJGMmZFZ0JacWo2OHJ0V2NwZzRvdzlESERob2dOVDJiYzVCSkVMTXBBRUhKQld4b0d1ck5EeFNLUGoxS3J1QU5RU3BmZmpDMXptT1crVERFRWV0WFlKNzNkVUJJNUhubTBxN0hpNzA5UUg0Y0dFMlo3UWwzV1NTei9LZWhOVWptaVhGdFl0SktUN2lpbGZIZlkraVNtVjBtZ0FEK0hnMGFRSHlHUWl5RExpcTVZYmp4QTVBQ2VlRFN5eGhuMnZab3djeTZ6UWF6alFVcDlILzlhR0c4M2g0ZzRlMUZ0THlscTBhNXhuMmxxTzJWN3pmT1VPOFFhTzkvOEFmY1RFdERraHo1UytLbjduUHFycHNrRnM3YThhZGJRK1VGSHRCUVBsbjZXOTZzbzJ4QUY1ZjExUEV3b2ZKd0diY2cvZFlWMlhjNXFDQkVzVzlCa3JMYUhXNzEyRFlMK1hxY3dtZy9CbFFaNW9ROXlLMU1BV2p6YllOK1I4OURvYTdHUDlFWllvQ2psaGZBaEx4MHppUHRUTW1uU0ZXNXJiSkdsT01Bem1YWnBHaDVpUUNUTU5RL2ZYM204Z0JxU0lNZFZob09tN3ZXUUpaREZYcVRtd0hLVWxXTnd2cWFKNWI1a0orT2Rwa0N2RHRMMVJtNWNsaUQvU2plemhGQi9kODhQMS9yTDZ2QlR6dTExZ3dsWHk4RU1Gd1pVcHgxV3BDejFhME5YeXd3am1yeTNsejFqN1JMZHhHZ09MdjBOOUg2UENKNEtOOGxlbkRmeUdkcUdQUjRaaGI1WkZDY1JpajIvWjduYmJSUFVTWlk3U3czMzA3dEE1emJ2azl5bW9nVlVLM3VjWU1sN0Nuek04OHdUeDN3WGYvVlV5RVVadFVZSFlpODZsOUJjeHRPdjB2VUh3WHJxakFXckJqTjFYSFZBcytzeWw4bS9ZMmM5ZXR5K0M4WmFwcGJhNkNVM0ZGb0pIeTBNRFdKMHUvNmtZd3Bvb0RidXIyL01GV1JZcDFzL20zdkJuVUM1SWpFeWxhdU1RemZ4Y0tOeHdKT2pTcHlobGU4akp4TFRVVTJzVGdOR0FBQmRyeGo4bUZxbjBieVRWam5lUEY0V1RUZUhReXV0TUhMQ2N0M1c2Mzh3VlhDb2VZNjI1RUpHaFRDcnF0NlA2OERlYWdvYS8rMXZiYkVrNEgvZUxlWFgyZUJsVUU4bDdST3UiLCJzaXRla2V5IjoiMzNmOTZlNmEtMzhjZC00MjFiLWJiNjgtNzgwNmUxNzY0NDYwIiwiZXhwIjoxNjY0ODI1MTk0LCJwZCI6MH0.xiKPDRqERmW53-zUbx1NuEVXDSS4um8ljI9gnClRJkk

W0_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5IjoiRjdtblRvTDN5VEZMTWlQeTFvWklRSlpZTUU0WWc1K2RkcG55QUpuUXgrUUUza296R090RUcvT2lOeGhFUStyZlF1b2IyTkJub0V2WDZQVEhPb29RQXJQMy9UR0lIVEFmaU5kanVaenRBNHZ3ZER4eEIyZnRRUS9maXhPekxEeWZLTmhmM2hXUzJMeUFtb1NwQUlGYUNKVWxYYktlSXgyUmR2anVldFVTYldzazd0QlVKRW9YdHM3dFF3eFdMQnZ6a0ZmeWRSWUJkUVF3VW5zYVdWNnE4bUNaVWw1Y2FpR055VXJ4bWV1Tm1KRmVrQnNWb3ByMTUvYUNCL2ZSM045Rjh4M1VZSGtxZ3FValBEWEsvSDRuVG1HbFhuL3ZXQWhTd2Q3TkpGdTNONHhqcElyeDRvcTlnTWMyOFJuTkRyYWFTVXo3V0F6UXA3dkxsNU0wZUpDN01JM3lZaEo3cGFzZ0NHUUhGK1luc1NDS25NaEJtTHQ1V1hvSDVDUy9rT2o0enNNeDlDOGJmTC9UbU5UVDdJZGY0UG1pN0h6aS9HU2UwU1N2eVVIMDlub055L3RZZ240RWU1NWMxSERzQmR0cUJiM1dIMU9JYzRnRHJCNHlNRVE4WC9RNEtDYm50bkF0UU56b3RDME1JZG5sMHdna0lLcFhXR3FweFRrbXNVb1YvRmVhNDM1TGhNT1BoQzdXWTFtbXBYYU8yUWJkN0dYTlluQVJPYVh4b0RJNzF3OERINkVGKzM3UGViMHNza0FrUm80R2FkQ0ZHRHJTbWRCZmViZmJXdVhVMHVqQ24yRkxsVG9XUkcreHl6aXZzL2RyRHZ3a2pCMDlQbHNiYWF3NC9JVFhqQWc1L3ZBZW9iNXFNN0NoTkZ1dTIrdDBiWEJIZkNCcGFaaFRYa01MUk5IS2phdVY4LytUd3BtTkVUMDNmZVJqVXA2OTFEYTd6QldyeTBhdnVoMTZVUXhHdDdzaXc2REdaTWZpNCtUOFZJeVF0TmVUZTEzaUhtaGJmTlRTa05PRnErSSs0dTFselVrQzRqWExSb2JjRlJXT21DSStrZ29RZVNNK0hqeURVd0RkSUg2WlhFQzdId1Z4Z0V0SXZ2UGl4aEQ2VUdMTWU3MGRKL3J2MDBBbUVUT0JQRFgzWTdNNlU4cnk3VnFJelhPYlZjZlhCY3NyWC95alJmSExLZ2U1ekhLZzFqdEtiLzBEVmtMdkhyMlJMaXhBNlBtWTJYTmp6QlpScXJMTDJkQkpackw4OUxnaVZzb1VOcnBXcE1ud29ZNUlJWkNCMEZHbFJ6SWF1R0x3dkNWUE9NNUVCbE1KWEZySlhqSGorQjNORDBRWm40SUhYdXZHekpQY1lDYXNpMmtlOEZIMHZlTWtDWExuck9JVHVQSk82S0hvaVVlMUVlQUU4MDNwUCtjVURZblNMQ1FuVTBMYWNMaDhkRVJ6aGk5SmV5bHZBalVYN3VEdlpoNE5uMnBBVXBieXdsTmdsOGxDVFNYZVFMa1RzbEdTMmVtUFZPckx0OWl0TmJzZ2h2Q1JWZStOaGd5aEZZeUh0cmI2dVZGVFZKZFVGQWJhWmxHaGx1UjNrQ2Q5OFdBazB1N0lkK2wyOE9kOG1uck9uS3hreS91aHNlUjQiLCJzaXRla2V5IjoiMzNmOTZlNmEtMzhjZC00MjFiLWJiNjgtNzgwNmUxNzY0NDYwIiwiZXhwIjoxNjY0ODI1NTExLCJwZCI6MH0.tA9KAbHPnFpUx20ANa0DZDPlj6r8YWV4QSDujZkODMc`

**Comment by AdminAnticaptcha** [comment]
Not related to the lib
