### ISSUE TITLE
waitForResult returns string instead of object

### ISSUE THREAD

**Issue by karlaugust1** [AdminAnticaptcha/anticaptcha-npm#15]
occasionally, the return of the method waitForResult is a simply a string, as belllow:
`03Az2X7wrwyYQxKhGNPKGPHCXb2w95bJ1lgT5RqF1movXrHsr5H9S`

and it should be an object like so:
`{"gRecaptchaResponse":"any_token","respKey":"","userAgent":"the_user_agent"}`

I'm using the lib in the latest version (1.0.27) with node v14

**Comment by lucasmoreiradev** [comment]
Same here

**Comment by AdminAnticaptcha** [comment]
fixed
