### ISSUE TITLE
Error with solveTurnstileProxyOn

### ISSUE THREAD

**Issue by kerlos** [AdminAnticaptcha/anticaptcha-npm#16]
I recieved error using solveTurnstileProxyOn method

`Received API error ERROR_INCORRECT_SESSION_DATA: Some of the required values for successive user emulation are missing. Missing property 'userAgent'`

**Comment by DemonMartin** [comment]
The error says exactly what's wrong... You're missing the 'userAgent'

**Comment by kerlos** [comment]
> The error says exactly what's wrong... You're missing the 'userAgent'

the problem is this function create json payload within the function which I cant directly add 'userAgent' to payload.


https://github.com/AdminAnticaptcha/anticaptcha-npm/blob/master/index.js#L631

**Comment by AdminAnticaptcha** [comment]
Issue is fixed at API level.
