### ISSUE TITLE
solveHCaptchaProxyOn is using my real IP?

### ISSUE THREAD

**Issue by DemonMartin** [AdminAnticaptcha/anticaptcha-npm#17]
![grafik](https://user-images.githubusercontent.com/49092993/212749449-df058824-44e4-46da-8436-1df148a3e78f.png)

My IP: 
![grafik](https://user-images.githubusercontent.com/49092993/212749535-aa9546e6-eb37-4003-b410-eae0d770bea8.png)

Code Used:
```js
let AntiCap = await ac.solveHCaptchaProxyOn(
                        "https://XXX:XXX/",
                        `${AddBot.body["captcha_sitekey"]}`,
                        "http",
                        SplitProxy[1][0],
                        SplitProxy[1][1],
                        SplitProxy[0][0],
                        SplitProxy[0][1],
                        CurrentFingerPrint.UserAgent
)
```

SplitProxy[1][0] = hostname in ip (I'm doing an dns lookup for geo.iproyal.com in my code)
SplitProxy[1][1] = port
SplitProxy[0][0] = Proxy name to auth
SplitProxy[0][1] = Proxy password to auth

**Comment by AdminAnticaptcha** [comment]
That's IP from which you've sent a task, not the proxy.
