### ISSUE TITLE
console.error messages cannot be turned off

### ISSUE THREAD

**Issue by a-l3x** [AdminAnticaptcha/anticaptcha-npm#5]
I don't want to have the `console.error` messages, but even `ac.shutUp();` doesn't prevent them. Looking into the code of the module  there is currently no way to do that without changing the module.

Example console.error message:
`ERR: Received API error ERROR_KEY_DOES_NOT_EXIST: Account authorization key not found in the system`

**Comment by AdminAnticaptcha** [comment]
Sorry but this is what you shouldn't ignore.

**Comment by a-l3x** [comment]
I have tests that are checking for an error object in case of wrong/no antigate key and the console.error is in that case the error log prints before the tests pass...
