### ISSUE TITLE
You can't solve invisible captcha's with this package

### ISSUE THREAD

**Issue by FoonkG** [AdminAnticaptcha/anticaptcha-npm#6]
![image](https://user-images.githubusercontent.com/54715823/110667780-e3ca6080-81ca-11eb-9c3d-244494fef424.png)
There is not way to set this option.

**Comment by SentoxAIO** [comment]
Looking for this option aswell

**Comment by AdminAnticaptcha** [comment]
Fixed, sorry for delay.

3rd parameter "true":
ac.solveRecaptchaV2Proxyless('http://DOMAIN.COM', 'WEBSITE_KEY', true)
